### ISSUE TITLE
Headingコンポーネントの実装

### ISSUE THREAD

**Issue by re-taro** [suzuka-kosen-festa/2024-hp#75]
- variantで３色を指定できるように
- childrenで中身を指定するように

![CleanShot 2024-05-28 at 11 12 04@2x](https://github.com/suzuka-kosen-festa/2024-hp/assets/68799469/37363383-371d-4921-af5c-565c0fa8ec66)

**Comment by re-taro** [comment]
ctx from slack

> これ今Headingやってる？
DOM構造的にはアレだけどHeading自体がなくなるかも

**Comment by ka1ut** [comment]
まだ手をつけていない
